name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    name: Test on ${{ matrix.os }} with Deno ${{ matrix.deno_version }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        deno_version: [1.40, 1.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno ${{ matrix.deno_version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test

      - name: Check Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint
